---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
        - name: webapp
          image: richardchesterwood/k8s-fleetman-webapp-angular:release0-5-arm64

---
apiVersion: v1
kind: Pod
metadata:
  name: queue-release-1
  labels:
    app: queue
    release: "1"

spec:
  containers:
    - name: queue
      image: richardchesterwood/k8s-fleetman-queue:release1-arm64