apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx-rs
  labels:
    app: nginx
    type: front-end
spec:
  template:
    metadata:
      name: nginx-pod
      labels:
        app: nginx
        type: front-end
    spec:
      containers:
        - name: nginx
          image: nginx
  replicas: 3
# apiVersion: apps/v1
# kind: ReplicaSet
# metadata:
#   name: nginx-rs
# spec:
#   replicas: 3
#   selector:
#     matchLabels:
#       app: nginx # This label selects the pods managed by this ReplicaSet
#  template:
#     metadata:
#       name: nginx
#      labels:
#         app: nginx
#       tier: frontend
#    spec:
#      containers:
#      - name: nginx
#        image: nginx

